### ISSUE TITLE
Errors in docker setup

### ISSUE THREAD

**Issue by teaglebuilt** [PacktPublishing/Hands-on-Microservices-with-Python#6]
So In the order docker compose file you are listing product db data in the order_db volume.
```
order_db:
    image: mysql:5.7.22
    volumes:
      - product-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=order
    restart: always
```

There is some issue with connecting to the databases when docker network is up and running.

if you run each byiteslf you will see this
```
user_db_1  | 2019-09-04T13:20:05.725272Z 2 [Note] Aborted connection 2 to db: 'user' user: 'root' host: '172.31.0.3' (Got an error reading communication packets)
```

Why have you created a user network, that is not mentioned in the frontend deploy compose file
